# Generated by Django 3.0 on 2020-09-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='survey',
            name='author',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
